server:
#  ssl:
#    enabled: true
#    key-store: classpath:rcc-rnd-d1.p12
#    key-store-password: ZSE4zse4
#    key-store-type: pkcs12
#    key-alias: rcc-rnd-d1-alias
#    key-password: ZSE4zse4
  port: 8080

management:
  info:
    env:
      enabled: true
    java:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health, info
      cors:
        allowed-origins: "*"
        allowed-methods: OPTIONS, GET, HEAD, POST, DELETE
        allowed-headers: "*"

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/radio}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:ZSE4zse4}
    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
        types:
          print:
            banner: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  pathsToMatch: /api/**

info:
  app:
    build: "0.0.1-SNAPSHOT" # manually from gradle
    name: "Северная часть Radio"
    version: CI_PIPELINE_IID
    commit: CI_COMMIT_SHORT_SHA
    branch: CI_COMMIT_BRANCH
